<a href="https://colab.research.google.com/github/nguyenchien-aik3/AI-K3/blob/main/%C4%91%E1%BB%93_%C3%A1n_p2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1:

In [3]:
import numpy as np
np.random.seed(123)


1. Cho x ∈ Rn và A ∈ Rm×n, hãy viết hàm tính tích x. A;

In [29]:
def vector_ma_tran(a, b, m, n):
  a = np.random.randint(low = a, high = b, size = m*n,).reshape((m, n))
  b = np.random.randint(low=a, high = b, size=n)
  y = b*a
  return(y)

2.1 Cho A, B ∈ Rm×n, hãy viết hàm tính A°B

In [19]:
def nhan_mt3(a,b,m,n):
  A = np.random.randint(low=a,high=b, size=m*n).reshape((m,n))
  B = np.random.randint(low=a,high=b, size=m*n).reshape((m,n))
  C = np.multiply(A,B)
  return(C)


2.2  Cho A, B ∈ Rm×n, hãy viết hàm tính AT. B;

In [26]:
def nhan_mt4(a,b,m,n):
  A = np.random.randint(low=a,high=b, size=m*n).reshape((m,n))
  B = np.random.randint(low=a,high=b, size=m*n).reshape((m,n))
  a = A.T
  C = np.dot(a, B)
  return(C)

3. Viết chương trình chính gọi các hàm trên.

In [18]:
nhan_mt3(2,3,2,3)

array([[4, 4, 4],
       [4, 4, 4]])

In [27]:
nhan_mt4(2,3,2,3)


array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [31]:
vector_ma_tran(2,3,2,3)

array([[4, 4, 4],
       [4, 4, 4]])

Câu 2:

In [ ]:
from sympy import *

In [ ]:
from sympy import *
def giai_ham(x, f, a):
  answer = limit(f, x, a)
  print('Kết quả giới hạn: ', answer)

def tinh_dao_ham(x, f):
  answer = diff(f, x)
  print('Kết quả đạo hàm: ', answer)

def nguyen_ham(x, f):
  answer = integrate(f, x)
  print('Kết quả nguyên hàm: ', answer)

def tich_phan(x, f, a, b):
  answer = integrate(f, (x, a, b))
  print('Kết quả tích phân: ', answer)

def main():
  x = symbols('x')
  giai_pt_he3(2, -5, 1, -5, 4, 2, -2, 2, 1, 1, -1, 0)
  giai_ham(x, (x*3-3*x**2)**1/3+(x**2-2*x)**1/2, +00)
  tinh_dao_ham(x, (2*x-1)/(x+2))
  nguyen_ham(x, (x / (x ** 2 + 1)))
  tich_phan(x, (1 - (x * 2 * tan(x)) / (x * 2 + cos(x) + x)), pi, (2 * pi / 3))
if _name_ == '_main_':
  main()

Câu 3:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sympy import symbols, Eq, solve
from sympy import *
fig, ax = plt.subplots()
x = np.linspace(start = -10.0, stop = 10.0, num = 200)
y = x**4 - 2*x**2 - 3
y1 = 4*x**3 - 4*x
y2 = 12*x**2 - 4
y3 = 24*x
ax.plot(x, y)
ax.plot(x, y1)
ax.plot(x, y2)
ax.plot(x, y3)
ax.set_xlabel('Trục hoành - x')
ax.set_ylabel('Trục tung - y')
ax.plot(x, y, label = r'$y = x^4 - 2x^2 - 3$')
ax.plot(x, y1, label = r'$y = 4x^3 - 4x$')
ax.plot(x, y2, label = r'$y = 12x^2 - 4$')
ax.plot(x, y3, label = r'$ y = 24x $')
ax.set_title('Đồ thị phương trình')
ax.legend()
plt.show()

In [ ]:
import numpy as np
np.random.seed(123)

def tao_ma_tran(a, b, m, n):
    y = np.random.randint(low = a, high = b, size = m*n,).reshape((m, n))
    print(y)
    return(y)
def nhan_ma_tran(n, y):
    T = n * y
    print(T)
def nhan_ma_tran2(x, y):
    T = np.multiply(x, y)
    print(T)
def nhan_mt3(n, x):
    y = tao_ma_tran(2, 8 , 3, 5)
    y_chuyenvi = y.T
    T = np.dot(x, y_chuyenvi)
    print(T)
def main():
    x = tao_ma_tran(2, 8, 3, 5)
    y = tao_ma_tran(2, 8, 3, 5)
    nhan_ma_tran(x, y)
    nhan_ma_tran2(x, y)
    nhan_mt3(3, x)
if _name_ == '_main_':
    main()
